- value: Web
  isOpen: true
  children:
    - value: Portfolio (this website!)
      path: Portfolio
    - value: M.O.R.A.C.E.
      path: Morace
    - value: React Games
      path: Games
    - value: SAPA TV Website
      path: Sapa
    - value: Random Poetry Generator
      path: RandomPoetry
    - value: Scryfall Random Card Fetcher
      path: ScryfallRandom

- value: Design
  isOpen: true
  children:
    - value: Packing List Show Identity
      path: PackingList
    - value: Ashby Library Signage
      path: AshbyLibrary
    - value: School of Chalk
      path: SchoolOfChalk
    - value: Hank Typeface
      path: Hank

- value: Music
  isOpen: true
  children:
    - value: Bleach Bloys
      path: BleachBloys

- value: Video
  isOpen: true
  children:
    - value: Irene H. Clark, Navajo Master Weaver
      path: IreneClark
