- value: Web
  children:
    - value: React
      children:
        - value: Tenzies
          path: Project1
    - value: Misc.
      children:
        - value: Random Poetry Generator
          path: RandomPoetry

- value: Design
  children:
    - value: Packing List Show Identity
      path: PackingList

- value: Music
