- value: Web
  children:
    - value: React
      children:
        - value: Games
          path: Games
        - value: Portfolio (this website!)
          path: Portfolio
    - value: PHP
      children:
        - value: M.O.R.A.C.E.
          path: Morace
        - value: SAPA TV Website
          path: Sapa
    - value: Misc.
      children:
        - value: Random Poetry Generator
          path: RandomPoetry

- value: Design
  children:
    - value: Packing List Show Identity
      path: PackingList

- value: Music
  children:
    - value: Bleach Bloys
      path: BleachBloys
